---
- name: Docker run
  docker_container:
    name: cadvisor
    image: gcr.io/google-containers/cadvisor:latest
    pull: "yes"
    recreate: "yes"
    privileged: "yes"
    state: "started"
    restart_policy: "unless-stopped"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    published_ports:
      - "0.0.0.0:{{ CADVISOR_PORT }}:8080"