---
- name: Docker run
  docker_container:
    name: "{{ CONTAINER_NAME }}"
    image: gcr.io/google-containers/cadvisor:{{ BUILD }}
    pull: "yes"
    recreate: "yes"
    privileged: "yes"
    cpu_period: "{{ DOCKER_CPU_PERIOD }}"
    cpu_quota: "{{ DOCKER_CPU_QUOTA }}"
    memory: "{{ DOCKER_MEMORY }}"
    state: "{{ CONTAINER_STATE }}"
    restart_policy: "unless-stopped"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    published_ports:
      - "0.0.0.0:{{ CADVISOR_PORT }}:8080"